### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by sunjay** [sunjay/pea#1]
This is an informal to-do list so I don't forget what I wanted to work on next.

- [x] merge Value and Obj and make Obj variants use Mutex explicitly
    * allows us to keep immutable values like functions immutable and also avoids the double indirection of matching on objects.
- [x] create a `ConstId` type with `unsafe fn new_unchecked(u16)` for deserializing and `into_u16` for serializing
- [x] zero-parameter function declarations and function calls
    * changes the grammar to make a program a list of decls
    * make `println_stmt` into `println_expr` and make calls a type of expr
    * running the program runs the zero-parameter `main` function
    * requires implementing a basic call stack
    * should be able to run:
    ```rust
    fn foo() {
        println!(34);
        println!(-921);
    }

    fn main() {
        println!(1);
        foo();
        foo();
        foo();
    }
    ```
- [x] add azure devops CI
    - [x] build and run hello world (smoke test)
    - [x] run unit tests
    - [x] run integration tests `run-pass`, etc.
    - [x] run unit tests and integration tests under [miri](https://github.com/rust-lang/miri)
- [x] add garbage collector
- [x] finish GC
    - [x] need to make `GcEntry` no longer be generic
    - [x] need an enum of all the types that can be allocated on the gc
    - [x] need a `FuncPtr` to store in call frames
    - [x] need to actually call the GC during execution
        - [x] have `gc::needs_collect` that `Interpreter` checks to determine when to do the mark + `gc::sweep()` calls
        - [x] should `gc::mark` call `trace`? Probably yes.
    - [x] need to mark all the reachable values
    - [x] need to make sure constants don't get accidentally freed
- [x] finish getting `Gc<[T]>` working (https://github.com/sunjay/pea/commit/2371e46f4ac183486aa293a689f253d384af64ba)
    - [x] since we already allocated `GcEntry<[T]>`, we don't even need the trait object for anything other than `Drop`
    - [x] if `needs_drop::<T>()`, we can store the `vtable` of `T` using `&dyn Trace` on `&array[0]` (need to be careful because drop is not needed if array size == 0)
    - [x] add a flag to header to indicate an array and store the layout in the header
    - [x] drop the values by moving them onto the stack, reconstructing their trait object, and then calling `ptr::drop_in_place` (no idea lmao)
    - [x] free the memory using `std::alloc::dealloc`
- [x] doesn't make sense to have `Gc<Bytes>` since `Bytes` is just `Vec<u8>`, we should have `struct Bytes(Gc<[u8]>)` (or something) and put that in `Value` instead of `Gc<Bytes>`
- [x] add GC logging behind a feature flag
- [x] print call stack on error
- [x] figure out a more maintainable way to structure the code in `Interpreter::step`
    * at minimum, we want a single function per instruction
    * might want to implement a trait over function pointers (or something) to make instruction argument passing more declarative
- [x] support recursive calls
    - [x] requires function name to be in scope before resolving function body
    - [x] limit call stack size (dynamically) and produce a stack overflow when we go past the capacity
- [x] variables + shadowing
    - [x] handle non-function calls as a runtime error (e.g. `13()`)
    - [x] add a name resolution step where all variables are unshadowed (and replaced with `DefId`s)
    - [x] function names should also be replaced with `DefId`s
    - [x] functions are not allowed to shadow other functions in the same scope
- [x] push a `Span` with each instruction added to `Bytecode` and use that to print file + line numbers in runtime error backtrace (need `SourceFiles` in `Interpreter`)
- [x] add a simple [pratt parser](https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html)
    - [x] support binary and unary operators
- [x] add assignment via `=` operator
- [x] support function parameters and argument passing via the value stack
    - [x] function parameters are not allowed to shadow
    - [x] need to check at runtime that the correct number of args is passed to the function
    - [x] limit to 255 parameters and 254 arguments (because of `self`)
- [x] support returning from functions
- [x] add support for string literals and operators on the string type like `+`
- [x] add `bool` value + literals
- [x] allow blocks to return their last expression (or default to unit)
    - [x] this replaces the push unit instruction we were adding at the end of all functions
- [x] add comparision operators `==`, `!=`, `>`, `<`, `>=`, `<=`
- [x] add conditionals (`if ... { ... } else if ... { ... } else if ... { ... } else { ... }`)
    - [x] support short-circuiting `&&` and `||`
    - [x] test `fib` function
- [x] add `while` loops
- [x] add `loop`
    - [x] add `break` and `continue`
- [x] add augmented assignment operators `+=`, `-=`, etc.
- [x] add list value type + list literals
- [x] add `print!()` macro
- [x] add `()` literal
- [x] add type annotations to functions in `ast` and `nir` (ignored by codegen for now)
    - [x] function argument and return type annotations
    - [x] variable type annotations
    - [x] ~~number literal suffixes~~ (delayed until we have more numeric types)
    - [x] update all tests to have type annotations
- [x] add a type checking pass on `nir`
    - [x] add an IR between `nir` and `codegen` called `cgenir` which has fully-resolved, concrete types for all values (all type variables resolved)
    - [x] add an IR called `tyir` between `nir` and `cgenir` that holds all of the type variables
    - [x] generate constraints and `tyir` from `nir`
    - [x] solve constraints to generate a substitution from type variables to concrete types
    - [x] generate `cgenir` from `tyir` using the substitution
    - [x] emit mismatched types errors
    - [x] use `cgenir` in `codegen`
- [x] add a byte literal `b'a'` that produces values of type `u8`
- [x] add native functions
- [x] add prelude
- [x] use prelude in name resolution
- [x] method calls
    - [x] parse method calls
    - [x] support `min` and `max` methods on `i64`
    - [x] replace unary/binary operator type inference with method call resolution
    - [x] remove `Add`, `Sub`, etc. opcodes and generate method calls instead
- [x] Use `Gc<T>` everywhere instead of `Arc<T>`
    - [x] Run an initial garbage collection before starting the interpreter to clean up any memory used by the compiler that is now unused
    - [x] Consider using `Gc<Scope>` in `nir` to avoid some unnecessarily expensive clones
- [ ] bug: replace all calls to `def_table.get` with something that looks up names based on the package ID of the `DefId` (test case: `let x = i64 {foo: 3}`)
- [ ] Add UTF-8 text type #3 
- [ ] Support format string in `println!` and make it a required first argument
- [ ] Add user defined types (`struct`) - #12 
    - [ ] field access
    - [ ] field assignment
- [ ] Add a separate namespace for types
    * Allows us to check that type annotations are only used with valid types
    * Avoids all cases where a variable name or function can be used as a type name
    ```rust
    // non_type_annotations.pea
    fn foo(x: foo) {
    }

    fn main() {
        let q: foo = foo;
    }
    ```
- [ ] Methods on user defined types (`impl`)
    - [ ] universal function call syntax (UFCS) `MyType::method(...)`    
- [ ] change "prelude" package to "core" and make "prelude" a submodule of "core" (still pass the right `package::Module` to name resolution)
- [ ] Add bottom type (the never type `!`) - see #8 
- [ ] Add parametric polymorphism (generics)
    - [ ] Add generic list methods
- [ ] add closures
	- [ ] syntax: `fn (p1, p2) { ... }` (always requires curly braces and uses an anonymous function)
	- [ ] occurs check
        ```rust
        fn main() {
            let f = |x| x;
            f(f);
        }
        ```
- [ ] support using integer literals for both `i64` and `u8` (and potentially other integral types)
   - [ ] make sure it is an error to assign a `u8` variable to a negative value
- [ ] add basic read line support (maybe something similar to the way `println` works now?)
- [ ] implement a [brainfuck interpreter](https://github.com/sunjay/dino/blob/master/tests/run-pass/todo/brainfuck.dino) (proves language is turing complete)
- [ ] support nested functions (i.e. functions defined within functions)
- [ ] desugar `println!("{} {}", a, b)` to a function call (formatting string arity checked at compile time)
- [ ] optimized bytecode/stack (no need to keep a type tag in Value if we know the type statically from the bytecode instruction used)
